
name: Android CI Release

on:
  push:
    branches: [ dev-release-build ]
  pull_request:
    branches: [ dev-release-build ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: ğŸ§± Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant Gradlew rights
        run: chmod +x gradlew

      - name: ğŸ§ª Run Tests
        run: ./gradlew test

      #      - name: ğŸ›  Build Project with Spotless Check
      #        run: ./gradlew spotlessCheck

      - name: â³ Build with Gradle
        run: ./gradlew build

      - name: ğŸ— Build APK
        run: bash ./gradlew assembleLiveRelease --stacktrace

      - name: ğŸš€ Upload APK ğŸ“±
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/live/release/*.apk
          retention-days: 3