name: Android CI Build aab


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute Permission for gradlew
        run : chmod +x gradlew
      # execute your unit tests
      - name: ğŸ§ª Unit Tests
        id: tests
        run: ./gradlew test
      # build a release app bundle
      - name: ğŸ—ï¸ Build app release bundle(AAB)
        id: BuildRelease
        run: ./gradlew bundleLiveRelease

      - name: ğŸš€ Upload AAB ğŸ“±
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/live/release/*.aab
          retention-days: 3